bootstrap_servers: localhost:9092
topic: test
interval: 0.2
pretrained_weight_path: D:\HK6\DS200\Project\src\real-time-video-violence-detection\pretrained_weight\mamonbest947oscombo-drive.hdfs
num_frames_to_predict: 120